### ISSUE TITLE
data not getting populated after initiation

### ISSUE THREAD

**Issue by apekshajit** [Bonitasoft-Community/getting-started-tutorial#6]
Hello, I have deigned the sample process as per the guidelines. I am using Bonitasoft 7.6.1, Please find .Bos file for reference and guide me further.
[Simple Document Review-1.0.zip](https://github.com/Bonitasoft-Community/getting-started-tutorial/files/1654008/Simple.Document.Review-1.0.zip)

![initiator level](https://user-images.githubusercontent.com/35583836/35251059-d701d802-001c-11e8-9c84-e0dc0bbb6c95.jpg)

![sample reviewer    @@@step](https://user-images.githubusercontent.com/35583836/35250956-5e284420-001c-11e8-9a0d-2dd3c8df517c.jpg)

**Comment by amottier** [comment]
The process in the getting started tutorial is named "Simple Travel Request" and in your screenshot the process is named "Document Review Request".

I think your issue is related to another example. Can you share a link to the documentation you follow to create or download the process you are having issue with?

Thanks.
